apiVersion: apps/v1
kind: Deployment
metadata:
  name: david-vizena-app
  namespace: david-vizena
  labels:
    app: david-vizena-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: david-vizena-app
  template:
    metadata:
      labels:
        app: david-vizena-app
    spec:
      serviceAccountName: david-vizena-app
      containers:
      - name: david-vizena-app
        image: davidvizena/hello-world:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: VAULT_ADDR
          value: "http://vault:8200"
        - name: VAULT_ROLE
          value: "david-vizena-app"
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: david-vizena-app
  namespace: david-vizena
  labels:
    app: david-vizena-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: david-vizena
  name: david-vizena-app-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: david-vizena-app-rolebinding
  namespace: david-vizena
subjects:
- kind: ServiceAccount
  name: david-vizena-app
  namespace: david-vizena
roleRef:
  kind: Role
  name: david-vizena-app-role
  apiGroup: rbac.authorization.k8s.io
